---
- name: Setup Yolo
  hosts: all
  become: true
  remote_user: root
  gather_facts: true
  become_method: sudo
  become_user: root
  become_flags: -H -S -n
   
  
  roles:

    - installDocker
    - gitclone
    - c