apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientapp
spec:
  selector:
    matchLabels:
      app: clientapp
  template:
    metadata:
      labels:
        app: clientapp
    spec:
      containers:
      - name: clientapp
        image: patrickngare/client:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: client_app
spec:
  selector:
    app: client_app
  ports:
  - port: 3030
    targetPort: 3030
