apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ip4_patel_stateful
spec:
  selector:
    matchLabels:
      app: db_app
  serviceName: mongo service 
  replicas: 2
  template:
    metadata:
      labels:
        app: db_app
    spec:
      containers:
      - name: db_app
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo-db
        volumeMounts:
        - name: www
          mountPath: /data/db 
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
