apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapp
spec:
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
      - name: backendapp
        image: patrickngare/backend:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ackend_app
spec:
  selector:
    app: ackend_app
  ports:
  - port: 5000
    targetPort: 5000
